add stdsim and stdstats
UtrechtUniversity/awesome-utrecht-university pull request #3
Opened 2021-11-15 16:10 UTC by japhir

This project shares all the more general functions as an R package, as well as the application of this code for this particular paper in a separate repository. The code itself is general enough that it may be useful to others, and hopefully the repository is set up as a good example.

2021-11-15 16:10 UTC, japhir commented
and it is shameless self-promotion ;-)

2021-11-16 11:30 UTC, kequach requested changes

2021-11-16 11:30 UTC, kequach commented on README.md
> +- [stdsim](https://github.com/japhir/stdsim/) - R package for Simulating Clumped Isotope standard statistics, associated [stdstats](https://github.com/japhir/stdstats) code that accompanies the paper
```suggestion
[stdstats](https://github.com/japhir/stdstats) - Simulation and plotting code for "Optimizing the use of carbonate standards to minimize uncertainties in clumped isotope data"
```
We would suggest to add stdstats instead after a license has been added. We opened an issue in the corresponding repository.
Optionally, also look at a possible Zenodo publication https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Thank you for the contribution!

2021-11-18 18:00 UTC, japhir commented
I've added the license and accepted the changes :)

2021-11-18 18:05 UTC, kequach requested changes

2021-11-18 18:05 UTC, kequach commented on README.md
> +[stdstats](https://github.com/japhir/stdstats) - Simulation and plotting code for "Optimizing the use of carbonate standards to minimize uncertainties in clumped isotope data"
```suggestion
- [stdstats](https://github.com/japhir/stdstats) - Simulation and plotting code for "Optimizing the use of carbonate standards to minimize uncertainties in clumped isotope data"
```
My bad, I missed the list symbol

2021-11-19 13:24 UTC, kequach approved these changes

2021-11-22 14:27 UTC, merged